server:
  port: 9090

---
# Turn off all console output unrelated to the MCP stdio transport
spring:
  config:
    activate:
      on-profile: '!sseTransport'
  main:
    banner-mode: off

logging:
  level:
    root: OFF
    org.springframework.ai.mcp: OFF
    org.springframework.ai.mcp.spec: OFF
    org.springframework: OFF

