spring:
  application:
    name: mcp-client

  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini